query Repositories($login: String!, $after: String) {
  user(login: $login) {
    
    

    repositories(first: 10, after: $after) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        id
        name
        url
        stargazerCount
        updatedAt
        

        
      }
    }
  }
}
